### ISSUE TITLE
getTests not refreshes, when testsUpdate occured

### ISSUE THREAD

**Issue by tjunussov** [ddgll/vue-idb#19]
VUEX version, 
Update not working as ADD if not found, but DEXIE's put works

if I call testsAdd, getTests refreshes data! OK!
but if i call testsUpdate for new Test( in my case InsertOrUpdate ) getTests not being refreshed

I think we could add this in **mutations**  section

```
[types[`${NAME}_UPDATE`]] (state, entity) {
	const index = state.collection.findIndex(e => e[_id] == entity[_id])
	if(index > -1){
		console.debug("UPDATEING");
		state.collection = [ ...state.collection.slice(0, index), entity , ...state.collection.slice(index+1) ]
	} else {
		console.debug("ADDING");
		state.collection = [ ...state.collection, entity ]
	}
	state.loading = true
},
```

**Comment by ddgll** [comment]
ADDED to 0.1.10 =) 
Thank's
